export const DataProjects = [
  {
    id: 1,
    title: "Dice-Game",
    imageSrc: require("../../assets/Projects/DiseGame.png"),
    description: "This is a game-Project. ",
    skills: "Html, Css, JavaScript",
    demo: "https://paimanmorsal.github.io/DiceGame/",
    source: "https://github.com/PaimanMorsal/GuessNumber.git",
  },
  {
    id: 2,
    title: "Piano",
    imageSrc: require("../../assets/Projects/piano.png"),
    description: "This is a Piano with Css.",
    skills: "Html & Css",
    demo: "https://paimanmorsal.github.io/CssPiano/",
    source: "https://github.com/PaimanMorsal/Piano.git",
  },
  {
    id: 3,
    title: "BitDog",
    imageSrc: require("../../assets/Projects/bitDog.png"),
    description: "This is a pet-store website.",
    skills: "Html & Css",
    demo: "https://paimanmorsal.github.io/BitDog-start-master/",
    source: "https://github.com/PaimanMorsal/BitDog-start-master.git",
  },
  {
    id: 4,
    title: "Animation Wheel",
    imageSrc: require("../../assets/Projects/AnimationWheel.png"),
    description: "It's an Animation Wheel.",
    skills: "Html & Css",
    demo: "https://paimanmorsal.github.io/AnimationWheel/",
    source: "https://github.com/PaimanMorsal/AnimationWheel.git",
  },
  {
    id: 5,
    title: "Color Remember",
    imageSrc: require("../../assets/Projects/ColorRemember.png"),
    description: "This is a game-project.",
    skills: "Html, Css, JavaScript",
    demo: "https://paimanmorsal.github.io/Color-Remember/",
    source: "https://github.com/PaimanMorsal/Color-Remember.git",
  },
  {
    id: 6,
    title: "My(CV)",
    imageSrc: require("../../assets/Projects/My-CV.png"),
    description: "This is a simple CV. ",
    skills: "Html & Css",
    demo: "https://paimanmorsal.github.io/My-CV/",
    source: "https://github.com/PaimanMorsal/My-CV.git",
  },
  {
    id: 7,
    title: "Employee Project",
    imageSrc: require("../../assets/Projects/EmployeeProject.png"),
    description: "It's a filter project.",
    skills: "Html, Css, React",
    demo: "https://employee-react-rho.vercel.app/",
    source: "https://paimanmorsal.github.io/EmployeePro/",
  },
  {
    id: 8,
    title: "Show Model",
    imageSrc: require("../../assets/Projects/ShowModel.png"),
    description: "Shows and hides models.",
    skills: "Html, Css, JavaScript",
    demo: "https://paimanmorsal.github.io/Show-Model/",
    source: "https://github.com/PaimanMorsal/Show-Model.git",
  },
  {
    id: 9,
    title: "Guess Number",
    imageSrc: require("../../assets/Projects/GuessNumber.png"),
    description: "This is a game project. ",
    skills: "Html, Css, JavaScript",
    demo: "https://paimanmorsal.github.io/Guess-Number/",
    source: "https://github.com/PaimanMorsal/Guess-Number.git",
  },
  {
    id: 10,
    title: "Portfolio with Css",
    imageSrc: require("../../assets/Projects/Portfolio.png"),
    description: " Simple portfolio with CSS. ",
    skills: "Html & Css",
    demo: "https://www.example.com",
    source: "https://www.github.com",
  },
  {
    id: 11,
    title: "Portfolio with React",
    imageSrc: require("../../assets/Projects/Portfolio(2).png"),
    description: " This is a portfolio. ",
    skills: "Html, Css, React",
    demo: "https://www.example.com",
    source: "https://www.github.com",
  },
  {
    id: 12,
    title: "Timer Challenge",
    imageSrc: require("../../assets/Projects/TimerChallenge.png"),
    description: "It is a game. ",
    skills: "Html, Css, React",
    demo: "https://time-challege.vercel.app/",
    source: "https://github.com/PaimanMorsal/TimerChallenge.git",
  },
  {
    id: 13,
    title: "Filter Project",
    imageSrc: require("../../assets/Projects/FilterProject.png"),
    description: "filter the datas.",
    skills: "Html, Css, React",
    demo: "https://filter-project-7ci7.vercel.app/",
    source: "https://github.com/PaimanMorsal/Filter-Project.git",
  },

  {
    id: 16,
    title: "Flex Gallery",
    imageSrc: require("../../assets/Projects/FlexboxGallery.png"),
    description: "This is a gallery. ",
    skills: "Html & Css",
    demo: "https://paimanmorsal.github.io/TrainJs-FlexboxGallery/",
    source: "https://github.com/PaimanMorsal/TrainJs-FlexboxGallery.git",
  },
  {
    id: 17,
    title: "Counter project",
    imageSrc: require("../../assets/Projects/counter.png"),
    description: "It helps you count.",
    skills: "Html, Css, React",
    demo: "https://counter-project-virid.vercel.app/",
    source: "https://github.com/PaimanMorsal/counter-project.git",
  },
  {
    id: 18,
    title: "Add User",
    imageSrc: require("../../assets/Projects/adduser.png"),
    description: "Adds user in webpage. ",
    skills: "Html, Css, React",
    demo: "https://add-user-self.vercel.app/",
    source: "https://github.com/PaimanMorsal/add-user.git",
  },
];
